version: "3.8"
services:

  app:
    container_name: pal-backend
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    networks:
      - pal
    depends_on:
      - db
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  db:
    image: postgres:12-alpine
    container_name: pal-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgsql-volume:/var/lib/postgresql/data:delegated
    networks:
      - pal

volumes:
  pgsql-volume:

networks:
  pal:
    driver: bridge