name: Full check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Authenticate npm with the GPR
      uses: jgierer12/npm-auth-gpr@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use npm CI
      run: npm ci

    - name: TypeScript Error Report
      uses: andoshin11/typescript-error-reporter-action@v1.0.2

    - name: Lint
      run: npm run lint

    - name: Compile
      run: tsc --diagnostics
