name: Full check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    
    - name: Check-out
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Authenticate npm with the GPR
      uses: ahmadnassri/action-github-registry-npm-proxy@v1.0.3
      with:
        github-token: ${{ secrets.NPM_TOKEN }}

    - name: Use npm CI
      run: npm ci

    - name: TypeScript Error Report
      uses: andoshin11/typescript-error-reporter-action@v1.0.2

    - name: Lint
      run: npm run lint

    - name: Compile
      run: tsc --diagnostics

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: 'https://docker.pkg.github.com'
          username: 'Polar-Animal-League'
          password: ${{ secrets.NPM_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          push: false
          tags: polar-animal-league/pal-backend:pr

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
